#!/usr/bin/env bash

echo "Starting MYSQL-connector"
if [[ -z "$START_TIMEOUT" ]]; then
    START_TIMEOUT=600
fi

start_timeout_exceeded=false
count=0
step=10

sleep 10

#FOUND=$(printf "GET / HTTP/1.0\r\n\r\n" | nc localhost 8083 | grep -e '200 OK')


while [[ -z $(printf "GET / HTTP/1.0\r\n\r\n" | nc localhost 8083 | grep -e '200 OK') ]]; do
    echo "waiting for kafka to be ready"
    sleep $step;
    count=$(expr $count + $step)
    if [ $count -gt $START_TIMEOUT ]; then
        start_timeout_exceeded=true
        break
    fi
done

if $start_timeout_exceeded; then
    echo "Not able to auto-create topic (waited for $START_TIMEOUT sec)"
    exit 1
fi

echo "Connect started.."

curl -X POST   -H "Content-Type: application/json"   --data '{ "name": "quickstart-jdbc-source", "config": { "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector", "tasks.max": 1, "connection.url": "jdbc:mysql://mmysql:3306/connect_test?user=confluent&password=confluent", "mode": "incrementing", "incrementing.column.name": "id", "timestamp.column.name": "modified", "topic.prefix": "quickstart-jdbc-", "poll.interval.ms": 1000 } }'   http://localhost:8083/connectors

curl -X POST -H "Content-Type: application/json" --data '{ "name": "quickstart-es-source", "config": { "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector", "tasks.max": 1, "topics": "quickstart-jdbc-test", "key.ignore": true, "connection.url": "http://elasticsearch1:9200", "type.name": "kafka-connect" } }' http://localhost:8083/connectors
